### ISSUE TITLE
All items make ash

### ISSUE THREAD

**Issue by Go-Wish** [pahimar/Equivalent-Exchange#1123] opened 2016-12-26 21:27 UTC
### What should have happened
When I put a iron block in the Calcinator it should have made minimum dust
### What actually happened
It made ash
### What steps do we have to follow so we can reproduce the issue
put iron block in Calcinator
### Version of Equivalent Exchange 3
Version 0.3.0.547
### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)
Shouldn't be necessary

This happens whatever I use, all items make ash.

**Comment by Merthew** [comment] 2016-12-28 16:37
I am having the same problem. I tested the problem with all vanilla items and all of them made ash.

**Comment by Go-Wish** [comment] 2017-01-11 00:37
Ok so partially solved the issue. I copied the energy values from my client and now I can make Minium Dust, but not Azure Dust or Verdant Dust. What should make those still only makes ash.

**Comment by mcynical** [comment] 2017-01-13 02:51
Research has told me this issue for me is caused by the value of minium being null, still don't know how others are claiming to be able to revalue it

**Comment by armorpower** [comment] 2017-07-25 14:10
i think i may have the same issue also is verdant dust in the mod? if so its not in mine for some reason i guess

**Comment by pahimar** [comment] 2017-10-02 01:12
Closing due to age

**Closed** 2017-10-02 01:13 UTC
