### ISSUE TITLE
Only receiving ash from calciner

### ISSUE THREAD

**Issue by clay237** [pahimar/Equivalent-Exchange#1109] opened 2016-09-10 21:30 UTC
### EquivalentExchange3-1.7.10-0.3.0.547

I am running EE3 on a FTB infinity server with a few extra mods.. hopefully that isn't the problem.

**Comment by pahimar** [comment] 2016-09-12 12:51
There are only two types of dust in that build; Ash and Minium

What is the EMC value of Minium dust in your instance? What are the EMC values of the items you calcined?

**Comment by clay237** [comment] 2016-09-13 00:47
NEI doesn't say

**Comment by chrijack1066** [comment] 2016-09-18 02:17
Hey Pahimar :)

Pardon me adding to this here - I'm having the same thing happen whereby regardless of what I'm calcinating, I'm only getting Ash.  Note - This is on servers only!  HOWEVER, in single player of the same [custom] pack, the calcinating part works perfectly fine.

On top of this, in the server I'm only getting 1 recipe for the Alchemical Coal - the one requiring the Verdant Dust.  Again, in single player, EE3 is spot on.

Assuming I get a notification email, feel free to prod me for more info if that helps.

Thanks and... Have a good day!! :D

Chrijack1066

**Comment by GrahamMThomas** [comment] 2016-10-24 05:25
Having same issue on my 1.7.10 server.

**Comment by pahimar** [comment] 2016-10-24 16:09
@clay237 Hold shift and hover over Minium Dust to see what the EMC value is. I need to know it to help troubleshoot.

@chrijack1066 each server/single player world has it's own set of values. That would be why you see it work some places and not others.

@GrahamMThomas without the same information as I asked above I cannot help you.

**Comment by GrahamMThomas** [comment] 2016-10-24 21:30
My minium dust does not have an EMC Value. I assumed this was the problem so I changed the setting in the config file from 'As needed' to 'always'. No dice.

**Comment by pahimar** [comment] 2016-10-25 18:25
Can you link me your energy values json and a copy of your fml client
latest log file. I'd like to find out why your minium dust has no value

**Comment by clay237** [comment] 2016-10-29 03:59
Here are the files sorry its taken me so long ive been at college and away from my server. 

[energy-values.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/559727/energy-values.txt)
[2016-10-27-1.log.gz](https://github.com/pahimar/Equivalent-Exchange-3/files/559728/2016-10-27-1.log.gz)

**Comment by SegFault22** [comment] 2016-10-29 21:04
I am having the same problem. All of the data files for energy values were missing the entries for minium dust, so I set the values with the chat-command, but the item still has no exchange value even after restarting the game several times.
It doesn't matter if the energy values are regenerated or not, this always happens.
It appears that EE3 is not loading the values for several items including minium dust, but is loading the values for other items. Seeing that many people have played using modpacks with EE3 and made videos about it, we should be able to find a version which didn't have this problem and see what was changed.

It may be significant that all of the videos featuring a player sucessfully making minium dust, also features the same player making the other dusts which got removed.

**Comment by pahimar** [comment] 2016-10-29 21:11
@clay237 that is an incomplete log file. Could you please upload/link to a full FML log for a play session where you experience only getting ash when you should get minium dust?

**Comment by SegFault22** [comment] 2016-10-29 21:18
I am having the same problem. All of the data files for energy values were missing the entries for minium dust, so I set the values with the chat-command, but the item still has no exchange value even after restarting the game several times.
It doesn't matter if the energy values are regenerated or not, this always happens.
It appears that EE3 is not loading the values for several items including minium dust, but is loading the values for other items. Seeing that many people have played using modpacks with EE3 and made videos about it, we should be able to find a version which didn't have this problem and see what was changed.

It may be significant that all of the videos featuring a player sucessfully making minium dust, also features the same player making the other dusts which got removed, and it is usually specifically said that all items within a certain energy value range will always be converted into the dust for that range, and there is no chance involved or a second slot.

It could also be helpful to upload compiled .jar files for the mod with the latest code, since it is such a hassle for everyone to do that on their own, and the mod has to be compiled at least once per build/change/whatever to tell if it is working or not, and java is designed such that the same .jar file can be run on any system which has a java VM supporting all of the functions which are used. That way, we could quickly try different versions of the code as it is being developed, instead of having to wait for a compiler to produce a .jar file identical to what everyone else produced with their compilers on whatever system.

**Comment by pahimar** [comment] 2016-10-29 21:30
@SegFault22 without logs I cannot help you. There are loads of people that are having things work properly, and I've seen it first hand where people can make Minium Dust after I deprecated the way to get the other dusts.

All builds I publish are instantly uploaded to http://ee3.pahimar.com as well as to Curse. There will not be any other way that I will publish compiled jars of the mod. It's INSANELY easy to compile a version of the mod (you just need Java installed which you have to have in order to play Minecraft anyways).

**Comment by SegFault22** [comment] 2016-10-29 22:25
Okay, I uploaded a relevant log file to some file sharing site. Note that it is massive, and it may take some time to find anything relevant in there, if there even is anything relevant within the log.

https://drive.google.com/uc?export=download&id=0B1s9eokqvkOKLWdsRHlOMGJDQlU

Also, I did not put anything into a calciner/calcinator that should produce minium dust when this log was created, since I have determined that the device works properly, and it does not output any minium dust simply because any item put into the device does not have an energy value at or above that of minium dust. For example, if minium dust had an energy-value set (properly set, not just existing as an entry in the file, but also loaded with the game and displayed when you hold shift while pointing at the item with the cursor) to 2, you would get it from logs and planks quite often, but if the energy value of minium dust were infinity or null, you would never be able to get it (as is the case). The same applies for ash, which you actually can get - if you set its entry to be without a value, it would be unobtainable.

I could attempt to change the energy-value of ash to 8192 (since it is produced by the calciner/calcinator), and see what happens when I try to calcinate/calcine different stuff - but it will take quite a while to load the world, since I have so many registered items and recipes.

**Comment by clay237** [comment] 2016-10-29 22:52
I apologize for not giving the needed file however I don't know what file you need. I've re done the tests with the same result shut the server down then found the log file for that up time and it doesn't give much info.

**Comment by clay237** [comment] 2016-10-29 23:14
http://www.screencast.com/t/WYwRsgxURg

**Comment by SegFault22** [comment] 2016-10-30 00:25
@clay237 Try looking at the Exchange Value for minium dust, in NEI. If it is none/null, then the calciner/calcinator is working properly (if the value of the item is at or above the value of minium dust, minium dust is produced instead of ash - the value of diamond is 8,192, which is not above null/infinity), and the problem is with how the exchange value of minium dust is configured.

If the file for items' energy levels is modified to have an entry for the minium dust (with the unlocalized name "EE3:alchemicalDust" and metadata 3), then it should display an energy value in-game and be produced by the calciner/calcinator. However, I am experiencing that the value is not assigned to minium dust even if there is an entry for it in all of the files in the ~/.minecraft/data/ee3/energy-values/ folder.

**Comment by pahimar** [comment] 2016-10-30 00:45
@SegFault22 you are incorrect on a number of fronts.

The energy value for Minium Dust is 8192 by default (https://github.com/pahimar/Equivalent-Exchange-3/blob/MC1.7.10/src/main/java/com/pahimar/ee3/init/EnergyValues.java#L162). If it doesn't have a value

The chance of you getting Minium Dust is defined by the following formula https://github.com/pahimar/Equivalent-Exchange-3/blob/MC1.7.10/src/main/java/com/pahimar/ee3/util/CalcinationHelper.java#L14-L33. This function drives a probability function that determines if you get Minium Dust or Ash. The probability is the energy value of the item being calcined divided by the energy value of Minium Dust. Therefore if your Minium Dust does not have an energy value, you will only get Ash.

I'm trying to determine why some people have no energy value for their Minium Dust.

**Comment by SegFault22** [comment] 2016-10-30 01:34
I didn't want to explain the probability thing, but basically if you use a diamond the chance of getting minium dust is 1/1, if they both have the same value of course, which it is or should be by default. If the value of minium dust is 0 or nil/null, only ash is given since 0 (or nil/null) div.by 1 produces 0. So you only have a chance to get the minium dust, if you calcinate something with less energy than the energy of minium dust.

It isn't the calcinator that is causing the problem, but it is where the problem is having its effect - so people think that the calcinator isn't working, until they find out that minium dust doesn't have an energy value assigned.

I didn't realize that the chance for getting ash was not calculated based on any value, but happens if the calcinator doesn't get the chance to produce a minium dust

**Comment by chrijack1066** [comment] 2016-11-03 17:40
Hey Pahimar,

Thanks for taking the time to reply.

I've scan read the above and my issue isn't half as complicated as others!  But, for my part, my issue is fixed.

To resolve - I took the 'values' file from the 'Data' folder contained in my SSP folder and copied it to the same location on my SMP server (which, I checked beforehand, and it was missing certain items' values, including minium stone/shards/all the fuels etc - a value was present for Ash).

I appreciate this doesn't relate to the thread, but are we meant to be able to craft the small & medium alchemical chests? - The recipes I have for these guys require verdant for the small and azure for the medium.  I can [now] craft the large using Minium dusts.  Please advise if they're meant to be craftable and I'll happily start/add to another thread if you'd prefer.

I have no idea how or why this initially happened.  If it helps to know how I setup my server then continue reading... I built a pack myself slowly adding mods (I seem to remember EE3 being one of the first ones) then, after troubleshooting compatibility issues, I created a server simply copying/pasting the mods over to my other computer.  I also copied and pasted all the configs as well.  I didn't, however, copy/paste the Data folder which I assume had been created and populated in the server folders whilst messing around.  I hadn't noticed anything wrong until I went to craft the minium dusts and hadn't thought to check the values file until just now. (Pardon this waffle... I write this in the hope it might give you a brain-spark into the "how"!!!!)

Anyway, from one Canadian to another... Thanks and "Have a good day"!! :D

Chrijack1066

**Comment by SegFault22** [comment] 2016-12-22 04:40
I have not bothered to test this issue with different other mods to see which one may cause a conflict, because I am working on something else that is more fruitful. If someone wants to test which one causes the problems, go through the various popular mods and their related addons - such as TE3, IC2, Buildcraft, Railcraft, Mystcraft, AE2, chickenbones' mods, EnderIO, TiC, GregTech, Mekanism, and so on. It is also important to test various combinations, as many of these mods have code that is only activated when others are present (compatibility stuff, or unpredictable malware in the case of GregTech with TiC)

If I ever bother to look at this again, it will probably be a long time from now. I have important work to do on important stuff - some of which requires that one becomes insane in order to comprehend it in a coherent and useful manner, and some of which is programming something which I promised to create a long time ago. Considering the state of humans' society and associated shenanigans at this time, I probably do not have much time to do a lot of this work; and I hope that you can understand the reason for my silence from now until whenever.

**Comment by armorpower** [comment] 2017-07-25 14:17
so just thought i should say my problem here so verdant dust doesnt seem to be in my single player world and i havent change any files in mods ever (dont want to risk chaos) so anything verdant dust wise i cant make and azure dust doesnt seem to be in the mod wether i got a bad file of the mod or its just not in idk but iron gives ash i have nei and it even shows that i dont have verdant dust or azure dust just ash and minium

**Comment by pahimar** [comment] 2017-10-02 01:13
Closing due to age

**Closed by pahimar** 2017-10-02 01:13 UTC
